### ISSUE TITLE
 node main.js | after update

### ISSUE THREAD

**Issue by Ewo33** [Siltaz/kingsguard-discord-bot#1]
bot errors pls fix cannot start

![image](https://user-images.githubusercontent.com/108514049/176843560-c1691e83-b4f0-423f-840d-057f7aa9deda.png)

**Comment by Siltaz** [comment]
did you created the .env file ?

**Comment by LeoneBrasco** [comment]
> did you created the .env file ?

I figured out, by working with different github projects (discordbots) and learnt me a lot but thanks :))
